# Устанавливаем базовый образ Go
FROM debian:bookworm-backports

# Устанавливаем необходимые утилиты
RUN apt update && apt install -y \
    curl \
    ca-certificates

RUN apt install --yes golang golang-github-streadway-amqp-dev

# Создаем рабочую директорию
WORKDIR /app

# Копируем остальные файлы проекта
COPY . .

# Сборка Go-приложения
RUN go build drogon/examples/rabbitmq/consumer
RUN go build drogon/examples/rabbitmq/producer

EXPOSE 8080
