services:
  drogon:
    image: docker.io/arvaliullin/drogon:v0.1
    ports:
      - "8080:8080"
    environment:
      - DATABASE_CONNECTION=postgresql://drogon_user:drogon_password@postgres:5432/drogon_db?sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=drogon_db
      - POSTGRES_USER=drogon_user
      - POSTGRES_PASSWORD=drogon_password
    ports:
      - "5432:5432"
    volumes:
      - ./init/init-db:/docker-entrypoint-initdb.d/
